export { default } from './Editor'
export { default as Canvas } from './Canvas'
export { default as Controls } from './Controls'
export { getVisiblePeaksFromCache } from './peaks'
export { drawCursor, drawWaveformBase } from './render'
